import {test,expect,type Page} from '@playwright/test';

const node=(page:Page,id:string)=>page.locator(`.react-flow__node[data-id="${id}"]`);
const trackModelRequests=(page:Page)=>{const requests:string[]=[];page.on('request',r=>{if(r.method()==='POST'&&/\/(runs|sources|jobs|source-jobs|continue-jobs)(?:\?|$)/.test(r.url()))requests.push(r.url())});return requests};
const currentProject=async(page:Page)=>{await expect(page.getByLabel('Open project')).not.toHaveValue('');const id=await page.getByLabel('Open project').inputValue();return (await page.request.get('/api/projects/'+id)).json()};

// These are user-facing contract tests: editing metadata must change the accepted model,
// the canvas symbols and the readable overview together, without requesting a model.
test('production portal has editable stacked assets, hosted controls, connections and readable evidence',async({page})=>{
 const requests=trackModelRequests(page);
 await page.goto('/');await page.getByRole('button',{name:/^Production portal/}).click();
 await expect(node(page,'request-db')).toBeVisible();
 const initial=await currentProject(page);
 expect(initial.components).toHaveLength(7);expect(initial.zones.map((z:any)=>z.id)).toEqual(['client','z1','z2']);
 await expect(node(page,'app-host').locator('.instance-count')).toHaveText('×2');
 await expect(node(page,'app-host').getByAltText('Hosted Zone firewall')).toBeVisible();
 await expect(node(page,'zone-firewall').locator('.virtual-marker')).toHaveText('VM');

 await node(page,'request-db').click();
 await page.getByLabel('Instance count',{exact:true}).fill('3');await page.getByLabel('Instance count',{exact:true}).press('Tab');
 await expect.poll(async()=>(await currentProject(page)).deployments.find((d:any)=>d.component_id==='request-db').quantity).toBe(3);
 await expect(node(page,'request-db').locator('.instance-count')).toHaveText('×3');
 await page.getByLabel('Redundancy arrangement',{exact:true}).selectOption('active_active');
 await expect.poll(async()=>(await currentProject(page)).deployments.find((d:any)=>d.component_id==='request-db').redundancy_mode).toBe('active_active');
 await page.getByLabel('Form factor',{exact:true}).selectOption('virtual');
 await expect(node(page,'request-db').locator('.virtual-marker')).toHaveText('VM');

 await node(page,'zone-firewall').click();
 await page.getByLabel('Hosted on',{exact:true}).selectOption('');
 await expect(node(page,'app-host').getByAltText('Hosted Zone firewall')).toHaveCount(0);
 await page.getByLabel('Hosted on',{exact:true}).selectOption('app-host');
 await expect(node(page,'app-host').getByAltText('Hosted Zone firewall')).toBeVisible();

 await page.getByRole('button',{name:'Connections',exact:true}).click();
 await page.getByRole('button',{name:'Edit connection employee-web',exact:true}).click();
 await page.getByLabel('Purpose for employee-web',{exact:true}).fill('employee self-service requests');
 await page.getByLabel('Protocol for employee-web',{exact:true}).fill('HTTPS');
 await page.getByLabel('Port for employee-web',{exact:true}).fill('8443');
 await page.getByRole('button',{name:'Save connection',exact:true}).click();
 await expect(page.getByRole('button',{name:'Edit connection employee-web',exact:true})).toBeVisible();
 const saved=await currentProject(page),connection=saved.interfaces.find((i:any)=>i.id==='employee-web');
 expect(connection.purpose).toBe('employee self-service requests');expect(connection.protocol).toBe('HTTPS');expect(connection.port).toBe(8443);
 await page.getByRole('button',{name:'Overview',exact:true}).click();
 await expect(page.getByRole('heading',{name:'What runs where',exact:true})).toBeVisible();
 await expect(page.locator('.overview-component').filter({hasText:'Request database'})).toContainText('3 declared instances. active active redundancy. Virtual component.');
 await expect(page.locator('.connection-summary')).toContainText('employee self-service requests over HTTPS (port 8443)');
 await page.getByLabel('Authored notes',{exact:true}).fill('Demo reviewer: confirm recovery targets before procurement.');await page.getByLabel('Authored notes',{exact:true}).press('Tab');
 await page.getByRole('button',{name:'Sources',exact:true}).click();
 await expect(page.getByText('Bundled synthetic demo',{exact:true})).toBeVisible();
 await expect(page.locator('.sources-content')).toContainText('Nothing here was fetched from your organisation or the web');
 await page.getByText(/^Read original passages/).click();
 await expect(page.locator('.source-passages article').first()).toBeVisible();
 await page.getByRole('button',{name:'Save / reopen',exact:true}).click();
 expect((await currentProject(page)).notes).toBe('Demo reviewer: confirm recovery targets before procurement.');
 expect((await currentProject(page)).interfaces.find((i:any)=>i.id==='employee-web').port).toBe(8443);
 expect(requests).toHaveLength(0);
});

test('robotics example separates production and trial zones, includes wireless and grouped AWS assets',async({page})=>{
 const requests=trackModelRequests(page);
 await page.goto('/');await page.getByRole('button',{name:/^Robotics testbed/}).click();
 await expect(node(page,'trial-robot')).toBeVisible();
 const project=await currentProject(page);
 expect(project.components).toHaveLength(14);expect(project.zones).toHaveLength(8);
 for(const id of ['prod-client','prod-z1','prod-z2','test-client','test-z1','test-z2','aws-z1','aws-z2'])await expect(node(page,id)).toBeVisible();
 await expect(node(page,'trial-ap')).toContainText('Trial wireless access point');
 await expect(node(page,'trial-host').getByAltText('Hosted Trial virtual firewall')).toBeVisible();
 await expect(node(page,'aws-api').locator('.cloud-marker')).toHaveText('AWS');
 await expect.poll(()=>page.locator('.arch-node img').evaluateAll(images=>images.every(image=>(image as HTMLImageElement).complete&&(image as HTMLImageElement).naturalWidth>0))).toBe(true);
 await page.locator('.assistant').evaluate(element=>{element.scrollTop=0});
 await page.screenshot({path:'../../reports/archie-robotics-testbed.png',fullPage:true});
 await page.getByLabel('Component category',{exact:true}).selectOption('AWS');
 await expect(page.locator('.asset-group')).toHaveCount(1);
 await expect(page.getByTitle('Add aws-ec2',{exact:true})).toBeVisible();
 await expect(page.getByTitle('Add workstation',{exact:true})).toHaveCount(0);
 await page.getByTitle('Add aws-ec2',{exact:true}).click();
 await expect.poll(async()=>(await currentProject(page)).components.length).toBe(15);
 expect((await currentProject(page)).components.find((c:any)=>c.asset_id==='aws-ec2').form_factor).toBe('virtual');
 await page.getByLabel('Component category',{exact:true}).selectOption('Devices & robotics');
 await expect(page.getByTitle('Add robot',{exact:true})).toBeVisible();
 await page.getByLabel('Component category',{exact:true}).selectOption('Networking');
 await expect(page.getByTitle('Add wireless-access-point',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'System overview',exact:true}).click();await expect(node(page,'production-system')).toBeVisible();
 await page.getByRole('button',{name:'Connection details',exact:true}).click();await expect(page.locator('.edge-label').first()).toContainText('initiator');
 await page.getByRole('button',{name:'Architecture',exact:true}).click();await expect(node(page,'trial-robot')).toBeVisible();
 expect(requests).toHaveLength(0);
});

test('global policy drafts are shared but applicability and checks belong to each project',async({page})=>{
 const requests=trackModelRequests(page);
 await page.goto('/');await page.getByRole('button',{name:/^Production portal/}).click();
 await expect(node(page,'portal-web')).toBeVisible();await expect(page.getByLabel('Open project')).not.toHaveValue('');const portalId=await page.getByLabel('Open project').inputValue();
 await page.getByRole('button',{name:'Policies',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Policy library',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Clear selection',exact:true}).click();
 await page.getByRole('button',{name:'Apply to project',exact:true}).click();
 await expect.poll(async()=>(await currentProject(page)).policy_ids).toEqual([]);
 const title='Synthetic trial retention review '+Date.now();
 await page.getByText('Add a local policy draft',{exact:true}).click();
 await page.getByLabel('Title',{exact:true}).fill(title);
 await page.getByLabel('Requirement',{exact:true}).fill('A human reviewer records the agreed retention period before trial telemetry is kept.');
 await page.getByLabel('When does it apply?',{exact:true}).fill('Trials that retain telemetry');
 await page.getByLabel('Search tags, separated by commas',{exact:true}).fill('trial,retention');
 await page.getByRole('button',{name:'Save to global library',exact:true}).click();
 const draft=page.locator('.policy-card').filter({hasText:title});
 await expect(draft).toBeVisible();await expect(draft).toContainText('Manual review');
 await expect(draft.getByRole('checkbox')).not.toBeChecked();
 expect((await currentProject(page)).policy_ids).toEqual([]);
 await draft.getByRole('checkbox').check();await page.getByRole('button',{name:'Apply to project',exact:true}).click();
 await expect.poll(async()=>(await currentProject(page)).policy_ids?.length).toBe(1);
 const selected=(await currentProject(page)).policy_ids[0];expect(selected).toMatch(/^LOCAL-/);
 await page.getByRole('button',{name:'Policy checks',exact:true}).click();
 await expect(page.locator('.finding')).toHaveCount(1);await expect(page.locator('.finding')).toContainText(title);await expect(page.locator('.finding')).toContainText('Manual review');

 await page.getByRole('button',{name:/^Robotics testbed/}).click();await expect(node(page,'trial-robot')).toBeVisible();
 await page.getByRole('button',{name:'Policies',exact:true}).click();
 await page.getByLabel('Search policy library',{exact:true}).fill(title);
 await expect(draft).toBeVisible();await expect(draft.getByRole('checkbox')).not.toBeChecked();
 expect((await currentProject(page)).policy_ids||[]).not.toContain(selected);
 const portal=await (await page.request.get('/api/projects/'+portalId)).json();expect(portal.policy_ids).toEqual([selected]);
 expect(requests).toHaveLength(0);
});

test('optional mock policy advice is explicit, free, read-only and marked stale after editing',async({page})=>{
 const modelRequests=trackModelRequests(page);let reviewPosts=0;
 page.on('request',request=>{if(request.method()==='POST'&&/\/policy-review(?:-jobs)?$/.test(request.url()))reviewPosts++});
 await page.goto('/');await page.getByRole('button',{name:/^Production portal/}).click();
 await expect(node(page,'portal-web')).toBeVisible();const before=await currentProject(page);
 expect(before.policy_ids).toHaveLength(17);
 await page.getByRole('button',{name:'Policy checks',exact:true}).click();
 const advice=page.locator('.ai-policy-review'),run=advice.getByRole('button',{name:'Try review format · free demo',exact:true});
 await expect(advice.getByRole('heading',{name:'Optional AI policy review',exact:true})).toBeVisible();
 await expect(run).toBeEnabled();expect(reviewPosts).toBe(0);
 const factCount=await page.locator('.finding').count();expect(factCount).toBeGreaterThan(0);
 await run.click();await expect(advice.getByText('Mock demonstration',{exact:true})).toBeVisible();
 await expect(advice.locator('.ai-policy-assessment')).toHaveCount(17);
 await expect(advice.locator('.ai-policy-meta')).toContainText(`Revision ${before.revision} · deterministic-policy-demo · $0.0000`);
 await expect(advice.locator('.ai-policy-boundary').first()).toContainText('no AI model is called');
 expect(await currentProject(page)).toEqual(before);await expect(page.locator('.finding')).toHaveCount(factCount);
 await page.screenshot({path:'../../reports/archie-policy-review.png',fullPage:true});
 await run.click();await expect(advice.locator('.ai-policy-meta')).toContainText('saved result');
 expect(await currentProject(page)).toEqual(before);
 await page.getByRole('button',{name:'Canvas',exact:true}).click();await node(page,'portal-web').click();
 await page.getByLabel('Object name',{exact:true}).fill('Portal web service reviewed');await page.getByLabel('Object name',{exact:true}).press('Tab');
 await expect.poll(async()=>(await currentProject(page)).components.find((c:any)=>c.id==='portal-web').name).toBe('Portal web service reviewed');
 const edited=await currentProject(page);expect(edited.revision).toBeGreaterThan(before.revision);
 await page.getByRole('button',{name:'Policy checks',exact:true}).click();
 await expect(advice.locator('.ai-policy-warning').filter({hasText:'This review is out of date.'})).toBeVisible();
 await run.click();await expect(advice.locator('.ai-policy-meta')).toContainText(`Revision ${edited.revision} · deterministic-policy-demo · $0.0000`);
 await expect(advice.locator('.ai-policy-warning').filter({hasText:'This review is out of date.'})).toHaveCount(0);
 await expect(advice.locator('.ai-policy-assessment')).toHaveCount(17);
 await expect(page.locator('.finding')).toHaveCount(factCount);expect(await currentProject(page)).toEqual(edited);
 const usage=await (await page.request.get(`/api/projects/${edited.id}/usage`)).json();expect(usage.calls).toBe(0);expect(usage.total).toBe(0);
 expect(reviewPosts).toBe(3);expect(modelRequests).toHaveLength(0);
});

test('authored portal demo document reviews facts then accepts a follow-up prompt end to end',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'New',exact:true}).click();
 await page.getByLabel('Upload document',{exact:true}).setInputFiles('../../fixtures/demos/portal/mock-input.docx');
 const review=page.getByRole('dialog',{name:'Here’s what will change',exact:true});
 await expect(review).toBeVisible();
 await expect(review.getByRole('heading',{name:'Add Portal web service',exact:true})).toBeVisible();
 await expect(review.getByRole('heading',{name:'Name this project “Portal web service architecture”',exact:true})).toBeVisible();
 await expect(review.locator('.review-items')).toContainText('Zone: Client · user devices.');
 await expect(review.locator('.review-items')).toContainText('Zone: Z1 · application services.');
 await expect(review.locator('.review-items')).toContainText('Zone: Z2 · protected data.');
 await expect(review.locator('.review-items')).toContainText('Hosted on Application hosts.');
 await expect(review.locator('.review-technical')).not.toHaveAttribute('open','');
 await expect(review.locator('.review-technical pre')).toBeHidden();
 await expect(review.locator('.review-items')).not.toContainText('"op"');
 await page.screenshot({path:'../../reports/archie-specification-review.png',fullPage:true});
 expect((await currentProject(page)).components).toHaveLength(0);
 expect((await currentProject(page)).name).toBe('New architecture');
 await review.getByRole('button',{name:'Review later',exact:true}).click();
 await expect(review).toBeHidden();expect((await currentProject(page)).components).toHaveLength(0);
 await page.getByRole('button',{name:'Review proposed changes',exact:true}).click();await expect(review).toBeVisible();
 await review.getByRole('button',{name:'Accept changes',exact:true}).click();
 await expect(review).toHaveCount(0);
 await expect.poll(async()=>(await currentProject(page)).components.length).toBe(7);
 await expect(page.getByRole('heading',{name:'Portal web service architecture',level:1,exact:true})).toBeVisible();
 await expect(page.getByLabel('Open project').locator('option:checked')).toHaveText('Portal web service architecture');
 await expect(page.getByText('Uploaded document',{exact:true})).toBeVisible();
 await page.getByLabel('Architecture prompt',{exact:true}).fill('Rename Portal web service to Employee self-service portal');
 await page.getByRole('button',{name:'Preview proposed changes',exact:true}).click();
 await expect(review.getByRole('heading',{name:'Rename Portal web service to Employee self-service portal',exact:true})).toBeVisible();
 await expect(review.locator('.review-technical pre')).toBeHidden();
 expect((await currentProject(page)).components.find((c:any)=>c.id==='portal-web').name).toBe('Portal web service');
 await page.getByRole('button',{name:'Accept changes',exact:true}).click();
 await expect.poll(async()=>(await currentProject(page)).components.find((c:any)=>c.id==='portal-web').name).toBe('Employee self-service portal');
 await page.getByRole('button',{name:'Canvas',exact:true}).click();await expect(node(page,'portal-web')).toContainText('Employee self-service portal');
 await page.getByRole('button',{name:'Overview',exact:true}).click();await expect(page.locator('.overview')).toContainText('Employee self-service portal');
 await page.getByRole('button',{name:'Sources',exact:true}).click();await expect(page.getByText('Your prompt',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Save / reopen',exact:true}).click();
 const saved=await currentProject(page);expect(saved.interfaces).toHaveLength(4);expect(saved.deployments.find((d:any)=>d.component_id==='portal-app').quantity).toBe(2);
 await expect(page.getByRole('button',{name:'Undo',exact:true})).toBeEnabled();
 await page.getByLabel('Architecture prompt',{exact:true}).fill('Rename this project to Employee services');
 await page.getByRole('button',{name:'Preview proposed changes',exact:true}).click();
 await expect(review.getByRole('heading',{name:'Name this project “Employee services”',exact:true})).toBeVisible();
 expect((await currentProject(page)).name).toBe('Portal web service architecture');
 await review.getByRole('button',{name:'Accept changes',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Employee services',level:1,exact:true})).toBeVisible();
 await expect(page.getByLabel('Open project').locator('option:checked')).toHaveText('Employee services');
 const renamed=await currentProject(page);expect(renamed.components).toEqual(saved.components);expect(renamed.interfaces).toEqual(saved.interfaces);
 await page.getByRole('button',{name:'Undo',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Portal web service architecture',level:1,exact:true})).toBeVisible();
 await expect(page.getByLabel('Open project').locator('option:checked')).toHaveText('Portal web service architecture');
 await expect(page.getByRole('alert')).toHaveCount(0);
});

test('document preflight explains the file, provider, spending limit and partial coverage without a live call',async({page})=>{
 let preflights=0,interpretations=0;
 await page.route('**/api/projects/*/source-preflight',async route=>{
  preflights++;await route.fulfill({json:{provider:'openai',requests:2,unprocessed_batches:1,max_cost_usd:.2,unsupported_pages:[3]}});
 });
 // Fail closed if this test accidentally reaches a real interpretation endpoint.
 await page.route('**/api/projects/*/sources',async route=>{interpretations++;await route.abort()});
 await page.route('**/api/projects/*/runs',async route=>{interpretations++;await route.abort()});
 await page.goto('/');await page.getByRole('button',{name:/^Production portal/}).click();
 await expect(node(page,'portal-web')).toBeVisible();const before=await currentProject(page);
 await page.getByLabel('Provider',{exact:true}).selectOption('openai');
 await page.getByLabel('Upload document',{exact:true}).setInputFiles('../../fixtures/demos/portal/techspec.docx');
 const plan=page.locator('.processing-plan');
 await expect(plan.getByRole('heading',{name:'Read this specification?',exact:true})).toBeVisible();
 await expect(plan.locator('.document-name')).toHaveText('techspec.docx');
 await expect(plan).toContainText('read this document using OpenAI');
 await expect(plan).toContainText('existing design will stay unchanged until you accept');
 await expect(plan).toContainText('1 more section group will need a later read');
 await expect(plan).toContainText('Pages 3 have no readable text');
 await expect(plan).toContainText('Cloud spending limit for this read: $0.20');
 await expect(plan).toContainText('Selected document text will be sent to OpenAI');
 await expect(plan.getByRole('button',{name:'Read and propose a design',exact:true})).toBeVisible();
 expect(await currentProject(page)).toEqual(before);
 await plan.getByRole('button',{name:'Cancel',exact:true}).click();await expect(plan).toHaveCount(0);
 expect(await currentProject(page)).toEqual(before);expect(preflights).toBe(1);expect(interpretations).toBe(0);
});

test('narrow browser keeps its canvas usable with accessible overlay panels and scrolling tabs',async({page})=>{
 await page.setViewportSize({width:640,height:800});
 await page.addInitScript(()=>localStorage.setItem('archie.workspace',JSON.stringify({left:true,right:true,leftWidth:272,rightWidth:244})));
 await page.goto('/');
 await expect(page.locator('.assistant')).toBeHidden();await expect(page.locator('.inspector-panel')).toBeHidden();
 const noOverflow=()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth);
 expect(await noOverflow()).toBe(true);
 await page.getByLabel('Toggle Archie panel',{exact:true}).click();await expect(page.locator('.assistant')).toBeVisible();
 await page.getByRole('button',{name:/^Production portal/}).click();await expect(node(page,'portal-web')).toBeVisible();
 await page.getByLabel('Collapse Archie panel',{exact:true}).click();await expect(page.locator('.assistant')).toBeHidden();
 await expect(page.getByLabel('Toggle Archie panel',{exact:true})).toHaveAttribute('aria-expanded','false');
 await page.getByRole('button',{name:'Overview',exact:true}).click();await expect(page.getByRole('heading',{name:'What runs where',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Sources',exact:true}).click();await expect(page.getByRole('heading',{name:'Sources and evidence',exact:true})).toBeVisible();
 await page.getByLabel('Toggle Inspector panel',{exact:true}).click();await expect(page.locator('.inspector-panel')).toBeVisible();
 await page.getByLabel('Collapse Inspector panel',{exact:true}).click();await expect(page.locator('.inspector-panel')).toBeHidden();
 await page.getByRole('button',{name:'Canvas',exact:true}).click();
 const width=(await page.getByRole('region',{name:'Architecture canvas'}).boundingBox())!.width;expect(width).toBeGreaterThanOrEqual(620);
 expect(await noOverflow()).toBe(true);
 await page.screenshot({path:'../../reports/archie-narrow-browser.png',fullPage:true});
});

test('delete moves a project to Trash and restore keeps sources, edits and undo history',async({page})=>{
 const requests=trackModelRequests(page);
 await page.goto('/');await page.getByRole('button',{name:/^Production portal/}).click();
 await expect(node(page,'portal-web')).toBeVisible();
 const original=await currentProject(page),pid=original.id;
 await page.getByRole('button',{name:'Overview',exact:true}).click();
 await page.getByLabel('Authored notes',{exact:true}).fill('Synthetic review note kept when this project is restored.');
 await page.getByLabel('Authored notes',{exact:true}).press('Tab');
 await expect.poll(async()=>(await currentProject(page)).notes).toBe('Synthetic review note kept when this project is restored.');
 const accepted=await currentProject(page);
 await page.getByRole('button',{name:'Delete project',exact:true}).click();
 await expect(page.getByLabel('Open project')).toHaveValue('');
 await expect(page.getByLabel('Open project').locator(`option[value="${pid}"]`)).toHaveCount(0);
 expect((await page.request.get('/api/projects/'+pid)).status()).toBe(404);
 await page.getByText(/^Trash \(\d+\)$/).click();
 const entry=page.locator(`.project-trash li[data-project-id="${pid}"]`);
 await expect(entry).toContainText(original.name);
 await entry.getByRole('button',{name:'Restore '+original.name,exact:true}).click();
 await expect(page.getByLabel('Open project')).toHaveValue(pid);
 await expect(node(page,'portal-web')).toBeVisible();
 await expect(entry).toHaveCount(0);
 const restored=await currentProject(page);
 expect(restored).toEqual(accepted);expect(restored.sources).toEqual(original.sources);expect(restored.claims).toEqual(original.claims);
 await page.getByRole('button',{name:'Undo',exact:true}).click();
 await expect.poll(async()=>(await currentProject(page)).notes).toBe(original.notes);
 expect(requests).toHaveLength(0);
});

test('Empty Trash requires confirmation, removes trashed projects permanently and preserves active projects',async({page})=>{
 let purges=0;const requests=trackModelRequests(page);
 page.on('request',request=>{if(request.url().endsWith('/projects/trash/empty'))purges++});
 await page.goto('/');await page.getByRole('button',{name:/^Production portal/}).click();
 await expect(node(page,'portal-web')).toBeVisible();const active=await currentProject(page);
 await page.getByRole('button',{name:'New',exact:true}).click();
 await expect(page.getByRole('heading',{name:'New architecture',exact:true})).toBeVisible();
 const unwanted=await currentProject(page);
 await page.getByRole('button',{name:'Delete project',exact:true}).click();
 await expect(page.getByLabel('Open project')).toHaveValue('');
 await page.getByLabel('Open project').selectOption(active.id);await expect(node(page,'portal-web')).toBeVisible();
 await page.getByText(/^Trash \(\d+\)$/).click();
 const entry=page.locator(`.project-trash li[data-project-id="${unwanted.id}"]`),empty=page.getByRole('button',{name:'Empty Trash',exact:true});
 await expect(entry).toBeVisible();
 page.once('dialog',dialog=>{expect(dialog.message()).toContain('Permanently remove');expect(dialog.message()).toContain(unwanted.name);expect(dialog.message()).toContain('cannot be undone');return dialog.dismiss()});
 await empty.click();await expect(empty).toBeEnabled();
 expect(purges).toBe(0);await expect(entry).toBeVisible();
 expect((await (await page.request.get('/api/projects/trash')).json()).some((item:any)=>item.id===unwanted.id)).toBe(true);
 page.once('dialog',dialog=>dialog.accept());await empty.click();
 await expect(page.getByText('Trash (0)',{exact:true})).toBeVisible();await expect(empty).toBeDisabled();
 expect(purges).toBe(1);await expect(entry).toHaveCount(0);
 expect((await page.request.post(`/api/projects/${unwanted.id}/restore`,{data:{}})).status()).toBe(404);
 expect(await currentProject(page)).toEqual(active);await expect(node(page,'portal-web')).toBeVisible();
 expect(requests).toHaveLength(0);
});
