import {useEffect,useState,useCallback} from 'react';
import {ReactFlow,Background,Controls,MiniMap,applyNodeChanges,useReactFlow,type Node,type Edge} from '@xyflow/react';
import ELK from 'elkjs/lib/elk.bundled.js';
import {Layers,Plus,Undo2,Download,RefreshCw} from 'lucide-react';
import {api,change,type Project,type ChangeSet,type Operation} from './api';
import {ArchitectureNode,ArchitectureEdge} from './Canvas';
import Inspector from './Inspector';
const nodeTypes={architecture:ArchitectureNode},edgeTypes={architecture:ArchitectureEdge};
export default function App(){
 const [project,setProject]=useState<Project|null>(null),[projects,setProjects]=useState<any[]>([]),[view,setView]=useState('logical'),[nodes,setNodes]=useState<Node[]>([]),[edges,setEdges]=useState<Edge[]>([]),[selected,setSelected]=useState(''),[catalogue,setCatalogue]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[panel,setPanel]=useState('Canvas'),[text,setText]=useState(''),[proposal,setProposal]=useState<ChangeSet|null>(null),[narrative,setNarrative]=useState(''),[provider,setProvider]=useState('mock'),[usage,setUsage]=useState<any>(null),[settings,setSettings]=useState<any>(null),[findings,setFindings]=useState<any>(null);
 const flow=useReactFlow();
 const safe=useCallback(async(fn:()=>Promise<any>)=>{setBusy(true);setError('');try{return await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}},[]);
 const refreshList=()=>api<any[]>('/projects').then(setProjects);
 useEffect(()=>{refreshList();api('/catalogue').then(setCatalogue);api('/settings').then(setSettings).catch(()=>{});},[]);
 const open=async(id:string)=>{setProject(await api('/projects/'+id));setSelected('');setProposal(null)};
 const create=async(reference?:string)=>{const p=await api<Project>('/projects',{name:reference?'VAP integration · '+reference:'New architecture',reference});setProject(p);await refreshList()};
 const execute=async(operations:Operation[],preview=false)=>{if(!project)return;const c=change(project,operations);if(preview)setProposal(await api(`/projects/${project.id}/preview`,c));else setProject(await api(`/projects/${project.id}/commands`,c));};
 useEffect(()=>{if(!project)return;api(`/projects/${project.id}/views/${view}`).then(g=>{
   setNodes(g.nodes.map((n:any)=>({id:n.id,type:'architecture',parentId:n.parentId||undefined,position:{x:n.x,y:n.y},style:{width:n.width,height:n.height},data:{...n,resize:(p:any)=>safe(()=>execute([{op:'placement',id:n.id,view:view as any,value:{width:p.width,height:p.height}}]))}})));
   setEdges(g.edges.map((e:any)=>({...e,type:'architecture',sourceHandle:e.route?.source_handle||'right',targetHandle:(e.route?.target_handle||'left')+'-in',data:{route:e.route,object_ids:e.object_ids}})));
 });api(`/projects/${project.id}/narrative`).then(n=>setNarrative(n.text));api(`/projects/${project.id}/usage`).then(setUsage).catch(()=>{});api(`/projects/${project.id}/findings`).then(setFindings).catch(()=>{});
 },[project,view]);
 const add=async(asset:string,position?:{x:number,y:number})=>{if(!project)return;const id='tmp:'+crypto.randomUUID();await execute([{op:'add',entity:'components',id,value:{name:asset.replaceAll('-',' '),role:asset,asset_id:asset,status:'proposed'}},{op:'add',entity:'deployments',id:'tmp:'+crypto.randomUUID(),value:{component_id:id,zone_id:null}},...(position?[{op:'placement',id,view:view as any,value:position} as Operation]:[])]);};
 const dragStop=async(_:any,n:Node)=>{if(!project)return;const oldParent=n.parentId;const absolute=oldParent?{x:n.position.x+(nodes.find(x=>x.id===oldParent)?.position.x||0),y:n.position.y+(nodes.find(x=>x.id===oldParent)?.position.y||0)}:n.position;
   const target=nodes.find(z=>z.data.role==='zone'&&absolute.x>=z.position.x&&absolute.y>=z.position.y&&absolute.x<z.position.x+Number(z.style?.width)&&absolute.y<z.position.y+Number(z.style?.height));
   if(n.data.role!=='zone'&&view!=='sv1'&&target?.id!==oldParent){const d=project.deployments.find(d=>d.component_id===n.id);if(d){await execute([{op:'update',entity:'deployments',id:d.id,value:{zone_id:target?.id||null}},{op:'placement',id:n.id,view:view as any,value:{x:absolute.x-(target?.position.x||0),y:absolute.y-(target?.position.y||0)}}],true);return;}}
   await execute([{op:'placement',id:n.id,view:view as any,value:{...n.position,locked:true}}]);};
 const layout=async()=>{const elk=new ELK();const graph=await elk.layout({id:'root',layoutOptions:{'elk.algorithm':'layered','elk.spacing.nodeNode':'65'},children:nodes.filter(n=>!n.parentId).map(n=>({id:n.id,width:Number(n.style?.width),height:Number(n.style?.height)})),edges:[]});await execute((graph.children||[]).map(n=>({op:'placement',id:n.id,view:view as any,value:{x:n.x||0,y:n.y||0,locked:false}})));flow.fitView();};
 const assist=async()=>{if(!project)return;const r=await api(`/projects/${project.id}/runs`,{...change(project,[{op:'notes',value:{}}]),prompt:text,provider});setProject(await api('/projects/'+project.id));setProposal(r.proposal);};
 const upload=async(file:File)=>{if(!project)return;const data=new FormData();data.append('file',file);const r=await fetch(`/api/projects/${project.id}/sources`,{method:'POST',body:data});const body=await r.json();if(!r.ok)throw new Error(body.message||'Upload failed');setProject(await api('/projects/'+project.id));setProposal(body.proposal||null);setPanel('Sources');};
 return <div className="workbench"><header><div className="brand"><Layers size={25}/><div>Architecture Workbench<small>LOCAL DESIGN STUDIO</small></div></div><span className="badge">SYNTHETIC · DEMONSTRATION ONLY</span><div className="header-right"><select aria-label="Provider" value={provider} onChange={e=>setProvider(e.target.value)}><option value="mock">Mock · free demonstration</option><option value="ollama">Ollama · local</option><option value="openai">OpenAI · cloud opt-in</option></select><span>rev {project?.revision||0} · ${Number(usage?.total||0).toFixed(4)}</span><button onClick={()=>setPanel('Settings')}>Settings</button></div></header>
 <aside className="assistant"><h2>Project workspace</h2><select aria-label="Open project" value={project?.id||''} onChange={e=>safe(()=>open(e.target.value))}><option value="">Open a saved project…</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><div className="button-row"><button onClick={()=>safe(()=>create())}><Plus size={14}/>New</button><button onClick={()=>safe(()=>create('A'))}>Load demo A</button><button onClick={()=>safe(()=>create('B'))}>B</button></div>
 <h2>Design assistant</h2><p className="muted">Propose an architecture or a focused change. Review it before accepting.</p><textarea aria-label="Architecture prompt" value={text} onChange={e=>setText(e.target.value)} placeholder="Add one configuration workstation; keep the layout." rows={5}/><button className="primary" disabled={!project||busy||!text.trim()} onClick={()=>safe(assist)}>Preview proposed changes</button><label className="upload">Upload DOCX or PDF<input aria-label="Upload document" type="file" accept=".docx,.pdf" disabled={!project} onChange={e=>e.target.files?.[0]&&safe(()=>upload(e.target.files![0]))}/></label>
 {proposal&&<section className="proposal"><h3>Review change set</h3><p>{proposal.operations.length} operations · based on revision {proposal.base_revision}</p><div className="operation-list">{proposal.operations.map((o,i)=><div key={i}>{o.op} {o.entity||o.view}: {String(o.value?.name||o.id)}<details><summary>Details</summary><pre>{JSON.stringify(o.value,null,2)}</pre></details></div>)}</div><div className="button-row"><button className="primary" onClick={()=>safe(async()=>{setProject(await api('/changes/'+proposal.id+'/accept',{}));setProposal(null)})}>Accept changes</button><button onClick={()=>safe(async()=>{await api('/changes/'+proposal.id+'/reject',{});setProposal(null)})}>Reject</button></div></section>}
 {project?.decisions.filter(d=>d.state==='unknown').slice(0,3).map(d=><section className="question" key={d.id}><strong>{d.question}</strong><select aria-label={d.question} defaultValue="" onChange={e=>{const answer=e.target.value==='Other'?window.prompt('Your answer'):e.target.value;if(answer)safe(()=>api(`/projects/${project.id}/answers`,{...change(project,[{op:'notes',value:{}}]),decision_id:d.id,answer}).then(setProject))}}><option value="" disabled>Select an answer</option>{[...d.options,'Other','Not decided'].map(v=><option key={v}>{v}</option>)}</select></section>)}
 <h2>Component library <span className="count">24</span></h2><div className="palette">{catalogue.map(a=><button key={a.id} draggable onDragStart={e=>e.dataTransfer.setData('asset',a.id)} onClick={()=>safe(()=>add(a.id))} disabled={!project} title={'Add '+a.id}><img src={'/api/assets/'+a.icon} alt=""/>{a.id.replaceAll('-',' ')}</button>)}</div></aside>
 <main><div className="project-bar"><div><h1>{project?.name||'Design with evidence'}</h1><small>{project?`${project.components.length} components · ${project.interfaces.length} interfaces · saved locally`:'Start with a synthetic reference or create a project.'}</small></div><div className="button-row"><button disabled={!project} onClick={()=>safe(async()=>setProject(await api(`/projects/${project!.id}/undo`,change(project!,[{op:'notes',value:{}}]))))}><Undo2 size={14}/>Undo</button><button disabled={!project} onClick={()=>safe(async()=>{await open(project!.id);await refreshList()})}>Save / reopen</button><button disabled={!project} onClick={()=>setPanel('Exports')}><Download size={14}/>Export</button></div></div>
 <nav>{['Canvas','Narrative','Interfaces','Findings','Sources'].map(p=><button key={p} className={panel===p?'active':''} onClick={()=>setPanel(p)}>{p}</button>)}</nav>
 {error&&<div role="alert" className="error">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}{busy&&<div className="busy" role="status">Working…</div>}
 {panel==='Canvas'&&<><div className="view-bar">{[['logical','Logical'],['sv1','SV-1-style'],['sv2','SV-2-style']].map(([id,title])=><button key={id} className={view===id?'active':''} onClick={()=>{setView(id);setSelected('')}}>{title}</button>)}<span>Presentation {project?.views[view]?.revision||0}</span><button disabled={!project} onClick={()=>safe(layout)}><RefreshCw size={13}/>Arrange view</button></div><div className="canvas" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const asset=e.dataTransfer.getData('asset');if(asset)safe(()=>add(asset,flow.screenToFlowPosition({x:e.clientX,y:e.clientY})))}}><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} edgeTypes={edgeTypes} onNodesChange={changes=>setNodes(n=>applyNodeChanges(changes,n))} onNodeClick={(_,n)=>setSelected(n.id)} onEdgeClick={(_,e)=>setSelected(e.id)} onNodeDragStop={(e,n)=>safe(()=>dragStop(e,n))} onConnect={c=>safe(()=>execute([{op:'add',entity:'interfaces',id:'tmp:'+crypto.randomUUID(),value:{source:c.source,target:c.target}}]))} onReconnect={(old,c)=>safe(()=>execute([{op:'update',entity:'interfaces',id:old.id,value:{source:c.source,target:c.target}}]))} fitView minZoom={.2} deleteKeyCode={null}><Background gap={22} color="#dbe3ea"/><Controls/><MiniMap nodeColor={n=>n.data.role==='zone'?'#dbeafe':'#1b7f79'}/></ReactFlow>{!project&&<div className="empty"><Layers size={48}/><h2>One architecture. Three perspectives.</h2><p>Build a traceable draft, inspect its assumptions,<br/>and refine it together on the canvas.</p><button className="primary" onClick={()=>safe(()=>create('A'))}>Explore synthetic VAP example</button></div>}</div></>}
 {panel==='Narrative'&&<div className="content"><p className="badge">Generated from accepted revision {project?.revision}</p><pre>{narrative}</pre><h3>Your notes</h3><textarea key={project?.revision} defaultValue={project?.notes} aria-label="Authored notes" onBlur={e=>project&&e.target.value!==project.notes&&safe(()=>execute([{op:'notes',value:{text:e.target.value}}]))}/></div>}
 {panel==='Interfaces'&&<div className="content"><table><thead><tr>{['ID','Source → target','Purpose','Data flow','Initiator','Protocol / port','Enforcement'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{project?.interfaces.map(e=><tr key={e.id} onClick={()=>{setSelected(e.id);setPanel('Canvas')}}><td>{e.id}</td><td>{e.source} → {e.target}</td><td>{e.purpose||'Not decided'}</td><td>{e.data_direction}</td><td>{e.initiator||'Not decided'}</td><td>{e.protocol||'?'} / {e.port??'?'}</td><td>{e.enforcement.join(', ')||'Unspecified'}</td></tr>)}</tbody></table></div>}
 {panel==='Sources'&&<div className="content"><h2>Sources and fact review</h2>{project?.sources.map(s=><section className="source" key={s.id}><h3>{s.name} · v{s.version}</h3><p>{s.kind} · {s.processed.length} processed / {s.unprocessed.length} unprocessed sections · {s.unsupported_pages.length} unsupported pages</p>{s.unprocessed.length>0&&<button onClick={()=>safe(async()=>{const r=await api(`/projects/${project.id}/sources/${s.id}/continue`,change(project,[{op:'notes',value:{}}]));setProject(await api('/projects/'+project.id));setProposal(r.proposal)})}>Process next sections</button>}{project.claims.filter(c=>c.source_id===s.id).map(c=><div className="claim" key={c.id}><span className="badge">{c.review}</span> <b>{c.target_id}.{c.field}</b><p>{c.excerpt}</p><small>{c.locator}</small></div>)}</section>)}</div>}
 {panel==='Findings'&&<div className="content"><h2>Fictional policy checks</h2><p>8 implemented predicates · 12 clauses require manual review. A pass applies only to supplied facts.</p>{findings?.findings?.map((f:any)=><section className={'finding '+f.result} key={f.clause_id}><b>{f.clause_id} · v{f.version}</b><span className="badge">{f.execution} · {f.result?.replaceAll('_',' ')}</span><p>{f.message}</p><small>Affected: {f.affected_ids?.join(', ')||'project'} · Evidence: {f.evidence?.join(', ')||'none supplied'}</small></section>)}</div>}
 {panel==='Settings'&&<div className="content"><h2>Provider and resource limits</h2><p>Cloud requires server-side opt-in. Mock is a deterministic fixture demonstration.</p><pre>{JSON.stringify(settings,null,2)}</pre></div>}
 {panel==='Exports'&&<div className="content"><h2>Export accepted snapshot</h2>{proposal&&<p className="error">Pending proposal is excluded.</p>}<div className="export-grid">{['json','svg','docx','md','csv','pattern'].map(format=><a key={format} href={`/api/projects/${project?.id}/exports/${format}?view=${view}`} download>{format.toUpperCase()}<small>{format==='svg'?'Review image':format==='pattern'?'Sanitised reusable pattern':'Accepted revision '+project?.revision}</small></a>)}</div><p>Native Visio: run the interactive Windows helper on a licensed desktop. Editability verification is reported separately.</p></div>}
 </main><Inspector project={project} selected={selected} view={view} execute={(ops,preview)=>safe(()=>execute(ops,preview))} clear={()=>setSelected('')}/>
 <footer><span className="dot"/>Local workspace · {provider==='mock'?'No model connection':'Explicit '+provider+' provider'}<span>Logical · SV-1-style · SV-2-style / simplified demonstrations</span></footer></div>
}

