import type {Project,Operation} from './api';
export default function Inspector({project,selected,view,execute,clear}:{project:Project|null,selected:string,view:string,execute:(ops:Operation[],preview?:boolean)=>Promise<any>,clear:()=>void}){
 const current=project?.components.find(c=>c.id===selected),system=project?.systems.find(s=>s.id===selected),zone=project?.zones.find(z=>z.id===selected),edge=project?.interfaces.find(e=>e.id===selected),placement=project?.views[view]?.placements[selected];
 const update=(entity:Operation['entity'],value:any)=>{const original=entity?project?.[entity].find(item=>item.id===selected):undefined;if(original&&Object.entries(value).every(([key,v])=>JSON.stringify((original as any)[key])===JSON.stringify(v)))return Promise.resolve();return execute([{op:'update',entity,id:selected,value}])};
 return <aside className="inspector"><h2>Inspector</h2>{!selected?<p className="muted">Select a component, zone or connector. Ordinary edits make no model calls.</p>:<><code>{selected}</code>{(current||system||zone)&&<label>Name<input aria-label="Object name" key={selected+(current?.name||system?.name||zone?.name)} defaultValue={current?.name||system?.name||zone?.name} onBlur={e=>update(current?'components':system?'systems':'zones',{name:e.target.value})}/></label>}
 {current&&<><label>Role<input aria-label="Component role" key={selected+current.role} defaultValue={current.role} onBlur={e=>update('components',{role:e.target.value})}/></label><label>Deployment zone<select aria-label="Deployment zone" value={project?.deployments.find(d=>d.component_id===selected)?.zone_id||''} onChange={e=>{const d=project!.deployments.find(d=>d.component_id===selected);execute([{op:d?'update':'add',entity:'deployments',id:d?.id||'tmp:'+crypto.randomUUID(),value:{component_id:selected,zone_id:e.target.value||null}}],true)}}><option value="">Unspecified / external</option>{project?.zones.map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select></label><p className="muted">{current.status} · {current.scope}<br/>Evidence: {current.evidence.join(', ')||'manual / proposed'}</p></>}
 {edge&&<>{['source','target','initiator'].map(field=><label key={field}>{field}<select aria-label={'Interface '+field} value={(edge as any)[field]||''} onChange={e=>update('interfaces',{[field]:e.target.value||null})}><option value="">Not decided</option>{project?.components.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>)}{['purpose','protocol','port','delivery'].map(field=><label key={field}>{field}<input aria-label={'Interface '+field} key={selected+field+(edge as any)[field]} defaultValue={(edge as any)[field]??''} onBlur={e=>update('interfaces',{[field]:field==='port'?(e.target.value?Number(e.target.value):null):e.target.value||null})}/></label>)}<label>Data direction<select aria-label="Data direction" value={edge.data_direction} onChange={e=>update('interfaces',{data_direction:e.target.value})}>{['unknown','source_to_target','target_to_source','bidirectional'].map(x=><option key={x}>{x}</option>)}</select></label><label>Enforcement references<input aria-label="Enforcement references" defaultValue={edge.enforcement.join(',')} onBlur={e=>update('interfaces',{enforcement:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></label></>}
 {(edge||selected.startsWith('aggregate:'))&&<><label>Line style<select aria-label="Line style" value={project?.views[view].routes[selected]?.style||'orthogonal'} onChange={e=>execute([{op:'route',id:selected,view:view as any,value:{style:e.target.value}}])}><option value="orthogonal">Right-angled</option><option value="straight">Straight</option></select></label><label>Manual route points (x,y; x,y)<input aria-label="Route points" key={selected+JSON.stringify(project?.views[view].routes[selected]?.points)} defaultValue={project?.views[view].routes[selected]?.points.map(p=>`${p.x},${p.y}`).join('; ')||''} onBlur={e=>execute([{op:'route',id:selected,view:view as any,value:{points:e.target.value?e.target.value.split(';').map(p=>{const [x,y]=p.split(',').map(Number);return {x,y}}):[],locked:!!e.target.value}}])}/></label></>}
 {current&&<p className="muted">Dragging changes layout only. Reassign a zone here to review the architecture change.</p>}{placement&&<><div className="pair">{['x','y','width','height'].map(field=><label key={field}>{field}<input type="number" aria-label={'Placement '+field} key={selected+field+(placement as any)[field]} defaultValue={(placement as any)[field]} onBlur={e=>Number(e.target.value)!==(placement as any)[field]&&execute([{op:'placement',id:selected,view:view as any,value:{[field]:Number(e.target.value),locked:true}}])}/></label>)}</div><label><input type="checkbox" checked={placement.locked} onChange={e=>execute([{op:'placement',id:selected,view:view as any,value:{locked:e.target.checked}}])}/>Keep manual placement</label></>}
 {(current||edge||zone)&&<button className="danger" onClick={()=>{if(window.confirm('Delete this object and its referenced interfaces?'))execute([{op:'remove',entity:current?'components':edge?'interfaces':'zones',id:selected,confirmed:true}]).then(clear)}}>Delete selected object</button>}</>}
 <div className="inspector-note"><b>Evidence before certainty</b><p>Unspecified facts stay unknown. Synthetic policies are fictional and require human review.</p></div></aside>
}
