import {useState} from 'react';
import type {Project,Operation} from './api';
import type {Interface} from '../../../packages/contracts/types';
type Props={project:Project,execute:(ops:Operation[])=>Promise<unknown>,show:(id:string)=>void};
function InterfaceRow({item,project,execute,show}:Props&{item:Interface}){
 const [editing,setEditing]=useState(false),[draft,setDraft]=useState(item),[saving,setSaving]=useState(false);
 const name=(id:string|null)=>project.components.find(c=>c.id===id)?.name||'Not decided';
 const begin=()=>{setDraft(structuredClone(item));setEditing(true)};
 const save=async()=>{setSaving(true);try{const {id,...values}=draft;const result=await execute([{op:'update',entity:'interfaces',id:item.id,value:values}]);if(result)setEditing(false)}finally{setSaving(false)}};
 const endpoint=(field:'source'|'target'|'initiator')=><select aria-label={`${field} for ${item.id}`} value={draft[field]||''} onChange={e=>setDraft(d=>{const next={...d,[field]:e.target.value||null} as Interface;if(field!=='initiator'&&next.initiator&&![next.source,next.target].includes(next.initiator))next.initiator=null;return next})}>{field==='initiator'&&<option value="">Not decided</option>}{project.components.filter(c=>field!=='initiator'||[draft.source,draft.target].includes(c.id)).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>;
 return <tr className={editing?'interface-editing':''}>
 <td><code>{item.id}</code><button className="text-button" onClick={()=>show(item.id)}>Show on canvas</button></td>
 <td>{editing?<>{endpoint('source')}<span className="muted">to</span>{endpoint('target')}</>:<>{name(item.source)}<br/><span className="muted">→ {name(item.target)}</span></>}</td>
 <td>{editing?<input aria-label={`Purpose for ${item.id}`} value={draft.purpose||''} onChange={e=>setDraft({...draft,purpose:e.target.value||null})}/>:item.purpose||'Not decided'}</td>
 <td>{editing?<><input aria-label={`Protocol for ${item.id}`} value={draft.protocol||''} onChange={e=>setDraft({...draft,protocol:e.target.value||null})}/><input type="number" min={0} max={65535} aria-label={`Port for ${item.id}`} value={draft.port??''} onChange={e=>setDraft({...draft,port:e.target.value?Number(e.target.value):null})}/></>:<>{item.protocol||'Not decided'}<br/><span className="muted">Port {item.port??'not decided'}</span></>}</td>
 <td>{editing?<>{endpoint('initiator')}<select aria-label={`Data direction for ${item.id}`} value={draft.data_direction} onChange={e=>setDraft({...draft,data_direction:e.target.value as Interface['data_direction']})}>{[['unknown','Direction not decided'],['source_to_target','Source → target'],['target_to_source','Target → source'],['bidirectional','Both directions']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></>:<>{name(item.initiator)}<br/><span className="muted">{item.data_direction.replaceAll('_',' ')}</span></>}</td>
 <td>{editing?<div className="enforcement-options">{project.components.filter(c=>/firewall|gateway|proxy|waf|switch/.test(c.asset_id)||draft.enforcement.includes(c.id)).map(c=><label key={c.id}><input type="checkbox" aria-label={`Enforce ${item.id} with ${c.name}`} checked={draft.enforcement.includes(c.id)} onChange={e=>setDraft({...draft,enforcement:e.target.checked?[...draft.enforcement,c.id]:draft.enforcement.filter(id=>id!==c.id)})}/>{c.name}</label>)}</div>:item.enforcement.map(name).join(', ')||'Not recorded'}</td>
 <td>{editing?<><button className="primary" disabled={saving} onClick={save}>Save connection</button><button disabled={saving} onClick={()=>setEditing(false)}>Cancel</button></>:<button onClick={begin} aria-label={`Edit connection ${item.id}`}>Edit</button>}</td>
 </tr>
}
export default function InterfacesTable(props:Props){return <div className="content interfaces-content"><div className="content-heading"><div><h2>Connections</h2><p>Edit the traffic each component exchanges. This is a design table; it does not deploy firewall rules.</p></div><span className="badge">Revision {props.project.revision}</span></div><div className="interface-table-scroll"><table><thead><tr>{['Connection','From → to','Purpose','Protocol / port','Session starts at / data flow','Enforcement',''].map((s,i)=><th key={i}>{s}</th>)}</tr></thead><tbody>{props.project.interfaces.map(i=><InterfaceRow key={i.id+':'+props.project.revision} {...props} item={i}/>)}</tbody></table></div>{!props.project.interfaces.length&&<p>No connections yet. Connect two components on the canvas to add one.</p>}</div>}
