import type {Project,Operation} from './api';
const label=(value:string)=>value.replaceAll('_',' ');
export default function Overview({project,execute}:{project:Project,execute:(ops:Operation[])=>Promise<unknown>}){
 const names=Object.fromEntries([...project.components,...project.zones].map(c=>[c.id,c.name]));
 const zones=[...project.zones.map(z=>({id:z.id,name:z.name})),{id:'',name:'Placement not decided / external services'}];
 const zoningAssumptions=project.claims.filter(c=>c.source_kind==='assistant_proposal'&&c.field==='proposed_zoning'&&c.review!=='rejected');
 const unknowns=project.decisions.filter(d=>d.state==='unknown');
 return <div className="content overview"><div className="content-heading"><div><h2>{project.name}</h2><p>A summary of the accepted design. Edits to components and connections appear here automatically.</p></div><span className="badge">Revision {project.revision}</span></div>
 <div className="overview-stats"><span><b>{project.components.length}</b> components</span><span><b>{project.interfaces.length}</b> connections</span><span><b>{unknowns.length}</b> open decisions</span></div>
 {project.notes&&<section className="overview-intro"><h3>Design notes</h3><p className="preserve-lines">{project.notes}</p></section>}
 {zoningAssumptions.length>0&&<section className="overview-intro"><h3>Proposed zoning</h3><p>This design includes {zoningAssumptions.length} zoning assumptions proposed by Archie. Review the rationale and supporting requirements in Sources. These choices do not confirm deployed segmentation or security approval.</p></section>}
 <h2>What runs where</h2><div className="overview-zones">{zones.map(zone=>{const members=project.components.filter(c=>(project.deployments.find(d=>d.component_id===c.id)?.zone_id||'')===zone.id);return !!members.length&&<section key={zone.id}><h3>{zone.name}</h3>{members.map(c=>{const d=project.deployments.find(d=>d.component_id===c.id);return <div className="overview-component" key={c.id}><img src={'/api/assets/'+c.asset_id+'.svg'} alt=""/><div><b>{c.name}</b><p>{label(c.role)}. {d?.quantity==null?'Instance count is not decided.':`${d.quantity} declared instance${d.quantity===1?'':'s'}.`}{d&&d.redundancy_mode!=='unknown'?` ${label(d.redundancy_mode)} redundancy.`:''}{c.form_factor==='virtual'?' Virtual component.':''}{d?.host_component_id?` Runs on ${names[d.host_component_id]}.`:''}</p></div></div>})}</section>})}</div>
 <h2>How the components communicate</h2>{!project.interfaces.length?<p>No connections have been defined yet.</p>:<ol className="connection-summary">{project.interfaces.map(i=><li key={i.id}><b>{names[i.source]} → {names[i.target]}</b><p>{i.purpose?label(i.purpose):'Purpose not decided'}{i.protocol?` over ${i.protocol}`:'. Protocol not decided'}{i.port!=null?` (port ${i.port})`:''}. {i.initiator?`${names[i.initiator]} starts the session.`:'Who starts the session is not decided.'} {i.enforcement.length?`Declared enforcement: ${i.enforcement.map(id=>names[id]).join(', ')}.`:'No enforcement point has been recorded.'}</p></li>)}</ol>}
 <h2>Decisions to make</h2>{unknowns.length?<ul className="open-decisions">{unknowns.map(d=><li key={d.id}>{d.question}</li>)}</ul>:<p className="muted">No clarification questions are pending. This does not mean every design detail has been specified.</p>}
 <section className="overview-evidence"><h2>Where this came from</h2><p>{project.sources.length} source{project.sources.length===1?'':'s'} and {project.claims.length} recorded claims support this design. Open Sources to inspect the original passages. Manually added components may have no source evidence.</p><p className="muted">{project.synthetic?'This is a synthetic demonstration. Policies are draft examples, not organisational approval.':'Policy results still require human review.'}</p></section>
 <label className="notes-label">Edit design notes<textarea key={project.id+project.revision} aria-label="Authored notes" defaultValue={project.notes} rows={4} onBlur={e=>{const text=e.target.value;if(text!==project.notes)execute([{op:'notes',value:{text}}])}}/></label>
 </div>
}
