import {useEffect,useMemo,useState} from 'react';
import {api,type Operation,type Project} from './api';
import './PoliciesPanel.css';

type Clause={id:string;title:string;text:string;version:string;pack:string;implementation:'implemented'|'manual_review';applicability:string[];exceptions:string;tags:string[]};
type Library={clauses:Clause[];legacy_ids:string[];presets:{id:string;name:string;policy_ids:string[]}[];synthetic:boolean};
type Props={project:Project|null;execute:(operations:Operation[])=>Promise<unknown>};
const sameIds=(a:string[],b:string[])=>a.length===b.length&&a.every(id=>b.includes(id));

export default function PoliciesPanel({project,execute}:Props){
 const [library,setLibrary]=useState<Library|null>(null),[search,setSearch]=useState(''),[selection,setSelection]=useState<string[]>([]),[onlySelected,setOnlySelected]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[adding,setAdding]=useState(false);
 const [draft,setDraft]=useState({title:'',text:'',applicability:'',exceptions:'',tags:''});
 useEffect(()=>{let current=true;api<Library>('/policies').then(value=>{if(current)setLibrary(value)}).catch(e=>{if(current)setError(e.message)});return()=>{current=false}},[]);
 const accepted=useMemo(()=>project?(project.policy_ids??library?.legacy_ids??[]):[],[project,library]);
 useEffect(()=>setSelection(accepted),[accepted]);
 const dirty=!sameIds(selection,accepted);
 const matches=(clause:Clause)=>{const text=[clause.id,clause.title,clause.text,...clause.tags].join(' ').toLowerCase();return search.toLowerCase().split(/\s+/).every(word=>text.includes(word))&&(!onlySelected||selection.includes(clause.id))};
 const visible=library?.clauses.filter(matches)||[];
 const packs=Array.from(new Set(visible.map(clause=>clause.pack)));
 const missing=selection.filter(id=>!library?.clauses.some(clause=>clause.id===id));
 const apply=async()=>{setSaving(true);setError('');try{await execute([{op:'policy_selection',value:{policy_ids:selection}}])}catch(e){setError((e as Error).message)}finally{setSaving(false)}};
 const add=async(event:React.FormEvent)=>{event.preventDefault();setAdding(true);setError('');try{await api<Clause>('/policies',{title:draft.title.trim(),text:draft.text.trim(),applicability:draft.applicability.trim(),...(draft.exceptions.trim()?{exceptions:draft.exceptions.trim()}:{}),tags:draft.tags.split(',').map(tag=>tag.trim()).filter(Boolean)});setLibrary(await api<Library>('/policies'));setDraft({title:'',text:'',applicability:'',exceptions:'',tags:''})}catch(e){setError((e as Error).message)}finally{setAdding(false)}};
 return <div className="content policies-panel"><div className="policies-intro"><h2>Policy library</h2><p>One shared library for every project. Choose the policies that apply to <strong>{project?.name||'a project'}</strong>, then apply the selection.</p><p className="muted">All bundled clauses are fictional demonstration drafts. Automated checks assess only recorded facts; manual reviews need a person. Neither is organisational approval.</p></div>
 {error&&<p className="error" role="alert">{error}</p>}
 {!library?<p>Loading the local library…</p>:<><div className="policy-selection-bar"><div><strong>{selection.length} selected</strong><small>{project?'Applies to this project only':'Open a project to choose applicability'}</small></div><button className="primary" disabled={!project||!dirty||saving} onClick={apply}>{saving?'Applying…':'Apply to project'}</button><button disabled={!dirty||saving} onClick={()=>setSelection(accepted)}>Discard selection changes</button></div>
 <div className="policy-presets"><span>Choose a starting set:</span>{library.presets.map(preset=><button key={preset.id} disabled={!project||saving} onClick={()=>setSelection(preset.policy_ids)}>{preset.name}</button>)}<button disabled={!project||saving} onClick={()=>setSelection([])}>Clear selection</button></div>
 {project?.policy_ids===null&&<p className="muted">This saved project uses the original 20 demo policies. Selecting another set will not change your other projects.</p>}
 <div className="policy-search"><input aria-label="Search policy library" placeholder="Search policies, e.g. backups, TLS, AWS…" value={search} onChange={event=>setSearch(event.target.value)}/><label><input type="checkbox" checked={onlySelected} onChange={event=>setOnlySelected(event.target.checked)}/>Selected only</label><span>{visible.length} of {library.clauses.length} policies</span></div>
 {missing.length>0&&<div className="finding insufficient_information"><p>These selected policies are missing from this machine’s library. Recreate or remove them before review.</p>{missing.map(id=><label className="missing-policy" key={id}><input type="checkbox" checked onChange={()=>setSelection(ids=>ids.filter(item=>item!==id))}/>{id}</label>)}</div>}
 {packs.map(pack=><section className="policy-pack" key={pack}><h3>{pack}</h3>{visible.filter(clause=>clause.pack===pack).map(clause=><article className={'policy-card'+(selection.includes(clause.id)?' selected':'')} key={clause.id}><div className="policy-card-heading"><label><input type="checkbox" aria-label={'Apply '+clause.id} disabled={!project||saving} checked={selection.includes(clause.id)} onChange={event=>setSelection(ids=>event.target.checked?[...ids,clause.id]:ids.filter(id=>id!==clause.id))}/><strong>{clause.title}</strong></label><span className={'policy-kind '+clause.implementation}>{clause.implementation==='implemented'?'Automated fact check':'Manual review'}</span></div><p>{clause.text}</p><details><summary>{clause.id} · v{clause.version} · Applicability and exceptions</summary><dl><dt>Use when</dt><dd>{clause.applicability.join('; ')}</dd><dt>Exceptions</dt><dd>{clause.exceptions}</dd><dt>Origin</dt><dd>{clause.pack==='Your local drafts'?'Locally authored draft; no approval asserted.':'Bundled synthetic policy draft; not an external standard.'}</dd></dl></details></article>)}</section>)}
 {!visible.length&&<p className="muted">No policies match this search.</p>}
 <details className="new-policy"><summary>Add a local policy draft</summary><p>Saved in the shared library. New clauses require manual review and apply to a project only after you select them.</p><form onSubmit={add}><label>Title<input required minLength={3} maxLength={140} value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})}/></label><label>Requirement<textarea required minLength={15} maxLength={2400} rows={3} value={draft.text} onChange={event=>setDraft({...draft,text:event.target.value})}/></label><label>When does it apply?<input required minLength={3} maxLength={500} value={draft.applicability} onChange={event=>setDraft({...draft,applicability:event.target.value})}/></label><label>Exceptions, if any<input maxLength={500} value={draft.exceptions} onChange={event=>setDraft({...draft,exceptions:event.target.value})}/></label><label>Search tags, separated by commas<input value={draft.tags} onChange={event=>setDraft({...draft,tags:event.target.value})}/></label><button className="primary" disabled={adding}>{adding?'Saving draft…':'Save to global library'}</button></form></details></>}
 </div>
}
