import {useEffect,useState} from 'react';
import {api} from './api';
import './ProposalHistory.css';
type Entry={id:string;state:'accepted'|'rejected';base_revision:number;prompt?:string|null;source_name?:string|null;provider?:string|null;created_at?:string|null;summary:string[];findings:string[]};
type Page={items:Entry[];next_cursor:number|null};
export default function ProposalHistory({projectId}:{projectId:string}){
 const [history,setHistory]=useState<Page>({items:[],next_cursor:null}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let active=true;setHistory({items:[],next_cursor:null});setError('');setBusy(true);api<Page>(`/projects/${projectId}/proposal-history`).then(result=>{if(active)setHistory(result)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[projectId]);
 const more=async()=>{setBusy(true);setError('');try{const result=await api<Page>(`/projects/${projectId}/proposal-history?before=${history.next_cursor}`);setHistory(current=>({items:[...current.items,...result.items],next_cursor:result.next_cursor}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <section className="content proposal-history" aria-label="Change history"><h2>Change history</h2><p>Follow-ups and reviewed changes you accepted or rejected. Undo changes the design; it keeps the original review decision here.</p>{error&&<p role="alert">{error}</p>}{!busy&&!history.items.length&&!error&&<p>No reviewed changes yet. Accepted and rejected drafts will appear here.</p>}{history.items.map(item=><article key={item.id} data-change-id={item.id}><div className="history-heading"><strong>{item.prompt||item.source_name||'Reviewed design change'}</strong><span className={'history-state '+item.state}>{item.state==='accepted'?'Accepted':'Rejected'}</span></div><small>Based on revision {item.base_revision}{item.provider?` · ${item.provider}`:''}{item.created_at?` · Proposed ${new Date(item.created_at).toLocaleString()}`:''}</small><details><summary>{item.summary.length} proposed change{item.summary.length===1?'':'s'}</summary><ul>{item.summary.map((text,i)=><li key={i}>{text}</li>)}</ul>{item.findings.length>0&&<><h3>Review notes</h3>{item.findings.map((text,i)=><p key={i}>{text}</p>)}</>}</details></article>)}{busy&&<p role="status">Loading history…</p>}{history.next_cursor!==null&&<button disabled={busy} onClick={more}>Load earlier changes</button>}</section>
}
