import type {Project} from './api';
export default function SourcesPanel({project,provider,continueSource}:{project:Project,provider:string,continueSource:(id:string)=>void}){
 const names=Object.fromEntries([...project.components,...project.interfaces.map(i=>({id:i.id,name:i.purpose||'Connection'})),...project.zones,...project.systems].map(x=>[x.id,x.name]));
 const origin=(source:Project['sources'][number])=>source.kind==='prompt'?'Your prompt':source.origin==='bundled_demo'||source.id==='reference-source'?'Bundled synthetic demo':source.origin==='upload'?'Uploaded document':'Source carried with this project';
 return <div className="content sources-content"><div className="content-heading"><div><h2>Sources and evidence</h2><p>These are the prompts and documents used to build this project. Nothing here was fetched from your organisation or the web. Bundled examples are synthetic.</p></div></div>
 {!project.sources.length&&<section className="source-empty"><h3>No source material yet</h3><p>Manual canvas edits are recorded in the project history. Upload a specification or use an architecture prompt to add source-linked evidence.</p></section>}
 {project.sources.map(s=>{const claims=project.claims.filter(c=>c.source_id===s.id);return <section className="source-card" key={s.id}><div className="source-title"><h3>{s.name}</h3><span className="badge">{origin(s)}</span></div><p>{claims.length} recorded claims · {s.processed.length} processed passages · {s.unprocessed.length} remaining · version {s.version}</p>{s.unsupported_pages.length>0&&<p className="error">Text could not be read on pages {s.unsupported_pages.join(', ')}.</p>}
 {s.unprocessed.length>0&&<button onClick={()=>continueSource(s.id)}>Process next sections · {provider}{provider==='openai'?' (uses budget)':''}</button>}
 <details className="source-passages"><summary>Read original passages ({s.passages.length})</summary>{s.passages.map(p=><article key={p.locator}><small>{p.locator}{p.heading?' · '+p.heading:''}</small><p className="preserve-lines">{p.text}</p></article>)}</details>
 {claims.map(c=><div className="claim" key={c.id}><div className="claim-heading"><b>{names[c.target_id]||c.target_id} · {c.field==='record'?'source statement':c.field.replaceAll('_',' ')}</b><span className="badge">{c.review}</span></div><blockquote>{c.excerpt}</blockquote><small>{s.name} · {c.locator}</small>{c.review==='confirmed'&&<span className="claim-note">Accepted as part of the design; still review the interpretation.</span>}</div>)}
 </section>})}</div>
}
